### ISSUE TITLE
Issue with "no directory" when running s21

### ISSUE THREAD

**Issue by mar-palt** [sebastian-zieba/PACMAN#10]
Hello! I'm just trying to run the pipeline with the example dateset for GJ 1214b, and I'm stuck on stage 21. I haven't had any issues when running the previous stages, but when I try to run s21, I get the error message: NotADirectoryError: [Errno 20] Not a directory: './run_2023-09-20_12-23-36_GJ1214_Hubble13021//extracted_lc/.DS_Store/lc_spec.txt'
I haven't changed anything in the src code, so I'm not sure why this issue is coming up and how to resolve it.
Thanks!

**Comment by sebastian-zieba** [comment]
Hi @mar-palt 
Thanks for raising the issue! This is indeed a bug that I wasn't aware of which I think only occurs on MACs. I will work on this in the next few days!
The basic problem is that PACMAN does not expect any hidden files or directories in the meta.workdir + "/extracted_lc/" directory. The solution would be to either exclude any files starting with a "." (so hidden files) or only include files that start with a "2". I think I will implement the latter because the directories will always start with a "2" as they are in the typical '%Y-%m-%d_%H-%M-%S' format. And current years (%Y) start with a "2". 

A new bugfix will be needed in the year 3000 then :)

I'll keep you updated.

Best,
Sebastian

**Comment by sebastian-zieba** [comment]
Hi @mar-palt 
This issue should be fixed now with the latest version of the code on master.
